modal
js-tasks-ru/htmlcss-20231222_fedor-dydykin pull request #10
Opened 2024-02-02 21:35 UTC by fedor-dydykin

2024-02-02 21:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-03 07:37 UTC, GSemikozov requested changes

2024-02-03 07:37 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +<div class="modal__wrapper" id="modal">
элемент блока? и блок внутри элемента? (папа сын сына)
в общем, именно здесь и ставим класс блока, modal__wrapper можно переименовать в modal, а modal тогда в modal__window и позиционировать абсолютом

2024-02-03 07:37 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +    <nav class="modal__nav">
это не навигация, заворачивать в nav не надо

2024-02-03 07:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-03 08:04 UTC, fedor-dydykin commented on 05-lection3/02-modal/index.html
> +<div class="modal__wrapper" id="modal">
если делать абсолютом, то у меня получается, что при вертикальном скроле модальные элементы уезжают наверх и уже не скрывают ничего.
![image](https://github.com/js-tasks-ru/htmlcss-20231222_fedor-dydykin/assets/145027589/bd0725b7-200c-4e3a-bc45-516e24b3bb0d)

2024-02-03 08:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-03 08:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-03 08:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-05 15:32 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +<div class="modal__wrapper" id="modal">
если весь блок позиционировать как fixed и растягивать на весь вьюпорт - width: 100vw; height: 100vh, то такой проблемы не будет (а modal__window - через абсолют). Если еще проблема в самом js скрипте который не превентит скрол, то ее в рамках задачи решать не надо)

2024-02-06 21:18 UTC, GSemikozov approved these changes

2024-02-06 21:18 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-02-06 21:18 UTC, GSemikozov requested changes
осталось поправить конфликты

2024-02-09 12:54 UTC, GSemikozov approved these changes

2024-02-09 12:54 UTC, merged