Skeleton
js-tasks-ru/htmlcss-20231222_fedor-dydykin pull request #7
Opened 2024-01-30 09:12 UTC by fedor-dydykin

2024-01-30 09:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-30 16:08 UTC, GSemikozov requested changes

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +:root {
если это глобальная переменная - то задаем в рут в main.css, если локальная - прямо в классе блока, root использовать в компонентах не надо

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    min-width: 579px;
минимальные ширину и высоту - удалим

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 80px;
ой, а зачем такой большой марджин? и ширину 100% не надо

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-top: -8px;
кажется лишним

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header-detail-item:first-child {
:first-child и :last-child не добавляют мобильности - мы жестко фиксируем положение элементов с разными ширинами на уровне css, что излишне (если захотим на первое место поставить более длинную полоску - не получится). Так что .skeleton__line - это элемент для всех линий, а разную ширину - задаем через модификаторы

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__main-data-item {
см выше

2024-01-30 16:08 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__main-data {
<img width="317" alt="Screenshot 2024-01-30 at 18 07 52" src="https://github.com/js-tasks-ru/htmlcss-20231222_fedor-dydykin/assets/6191270/2fb7507c-00ad-45d2-8a19-26b33d7bb82c">
точно 32?)

2024-02-01 13:24 UTC, fedor-dydykin commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__main-data {
ага, это потому что круг сжимался у меня когда flex и я сделал круг position: absolute. А тогда отступы другие.
flex-shrink: 0 помог это поправить - переделаю теперь на flex обратно)

2024-02-02 13:27 UTC, GSemikozov requested changes

2024-02-02 13:27 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +      <div class="skeleton__main-data-item skeleton__main-data-item_super-long"></div>
это тоже skeleton__header-detail-item)

2024-02-02 13:27 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +      <div class="skeleton__main-data-item skeleton__main-data-item_super-long"></div>
и это

2024-02-02 13:27 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 20px;
16

2024-02-03 07:31 UTC, GSemikozov approved these changes

2024-02-03 07:31 UTC, merged