tooltip and light-tooltip
js-tasks-ru/htmlcss-20231222_fedor-dydykin pull request #9
Opened 2024-02-02 19:51 UTC by fedor-dydykin

2024-02-02 19:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-05 15:35 UTC, GSemikozov approved these changes

2024-02-05 15:35 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-02-05 15:37 UTC, GSemikozov requested changes
надо поправить конфликт

2024-02-06 21:17 UTC, GSemikozov approved these changes

2024-02-06 21:17 UTC, merged